export const data = {
  bikes: [
    {
      image: './images/bikeImages/full_2021_grand-canyon-6_2615_bk-gy_P5.webp',
      brand: 'canyon',
      model: 'Grand Canyon 6',
      type: 'Trail',
      wheelSize: 29,
      price: 1049,
      rating: 3,
      numReviews: 12,
    },
    {
      image: './images/bikeImages/full_2021_grand-canyon-6-wmn_2616_pk-bk_P5.jpeg',
      brand: 'canyon',
      model: 'Grand Canyon 6 wmn',
      type: 'Trail',
      wheelSize: 29,
      price: 1049,
      rating: 4,
      numReviews: 12,
    },
    {
      image: './images/bikeImages/full_2021_grand-canyon-7-wmn_2618_tq-si_P5.webp',
      brand: 'canyon',
      model: 'Grand Canyon 7 wmn',
      type: 'Trail',
      wheelSize: 29,
      price: 1249,
      rating: 5,
      numReviews: 12,
    },
    {
      image: './images/bikeImages/full_2021_grand-canyon-8-wmn_2620_wh-mc_P5.jpeg',
      brand: 'Canyon',
      model: 'Grand Canyon 8 wmn',
      type: 'Trail',
      wheelSize: 29,
      price: 1449,
      rating: 5,
      numReviews: 12,
    },
    {
      image: './images/bikeImages/full_2022_grand-canyon-9_3153_bk-gy_P5.webp',
      brand: 'Canyon',
      model: 'Grand Canyon 9',
      type: 'Trail',
      wheelSize: 29,
      price: 1779,
      rating: 2.5,
      numReviews: 12,
    },
    {
      image: './images/bikeImages/vitus-sommet-29-crs.png',
      brand: 'Vitus',
      model: 'Sommet 29 CRS',
      type: 'Enduro',
      wheelSize: 29,
      price: 3959.99,
      rating: 3.5,
      numReviews: 12,
    },
    {
      image: './images/bikeImages/DomaneAL5Disc_21_33086_A_Primary.jpeg',
      brand: 'Trek',
      model: 'Domane AL 5 Disc',
      type: 'Gravel',
      wheelSize: 29,
      price: 2049,
      rating: 4,
      numReviews: 12,
    },
    {
      image: './images/bikeImages/full_2021_grand-canyon-6_2615_bk-gy_P5.webp',
      brand: 'Canyon',
      model: 'Grand Canyon 6',
      type: 'Trail',
      wheelSize: 29,
      price: 1049,
      rating: 3,
      numReviews: 12,
    },
    {
      image: './images/bikeImages/full_2021_grand-canyon-6-wmn_2616_pk-bk_P5.jpeg',
      brand: 'Canyon',
      model: 'Grand Canyon 6 wmn',
      type: 'Trail',
      wheelSize: 29,
      price: 1049,
      rating: 4,
      numReviews: 12,
    },
    {
      image: './images/bikeImages/full_2021_grand-canyon-7-wmn_2618_tq-si_P5.webp',
      brand: 'Canyon',
      model: 'Grand Canyon 7 wmn',
      type: 'Trail',
      wheelSize: 29,
      price: 1249,
      rating: 5,
      numReviews: 12,
    },
    {
      image: './images/bikeImages/full_2021_grand-canyon-8-wmn_2620_wh-mc_P5.jpeg',
      brand: 'Canyon',
      model: 'Grand Canyon 8 wmn',
      type: 'Trail',
      wheelSize: 29,
      price: 1449,
      rating: 5,
      numReviews: 12,
    },
    {
      image: './images/bikeImages/full_2022_grand-canyon-9_3153_bk-gy_P5.webp',
      brand: 'Canyon',
      model: 'Grand Canyon 9',
      type: 'Trail',
      wheelSize: 29,
      price: 1779,
      rating: 2.5,
      numReviews: 12,
    },
    {
      image: './images/bikeImages/vitus-sommet-29-crs.png',
      brand: 'Vitus',
      model: 'Sommet 29 CRS',
      type: 'Enduro',
      wheelSize: 29,
      price: 3959.99,
      rating: 3.5,
      numReviews: 12,
    },
    {
      image: './images/bikeImages/DomaneAL5Disc_21_33086_A_Primary.jpeg',
      brand: 'Trek',
      model: 'Domane AL 5 Disc',
      type: 'Gravel',
      wheelSize: 29,
      price: 2049,
      rating: 4,
      numReviews: 12,
    },
  ],
};
